### ISSUE TITLE
Update versions and release artifact

### ISSUE THREAD

**Issue by antonkw** [profunktor/munit-golden#11]
@gvolpe 
Hi!
Are there plans to maintain the project?
I wanted to use it but it appeared that there is no released artifact. Once I just sourced from github dependencies were too outdated.
Thanks

**Comment by gvolpe** [comment]
At the moment, no plans to work on this project as I'm focused on Scala 3 and most of the type-level machinery only works in Scala 2. Maintainers always welcome.
